/**
 * Shared helpers for the per-source fetch scripts (fetch-f1, fetch-nfl, ...).
 *
 * Each fetch script:
 *   1. pulls its source with fetchWithCache()
 *   2. normalizes to the shared event schema, using resolveBroadcast() for TV
 *   3. writes data/<source>.json
 *   4. calls rebuildCombined() to regenerate data/events.json + data/events.js
 *
 * Personal, non-commercial, low-frequency use. Raw responses are cached in
 * .cache/ so re-runs within CACHE_TTL_HOURS don't re-hit the APIs.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.resolve(__dirname, "..", "..");
export const DATA_DIR = path.join(ROOT, "data");
export const CACHE_DIR = path.join(ROOT, ".cache");

export const VIEWER_TZ = "America/Chicago";
export const CACHE_TTL_HOURS = 12;

// Per-source files merged into the combined feed, in this order.
export const SOURCE_FILES = ["f1.json", "nfl.json", "bayern.json"];

export async function fetchWithCache(url, { ttlHours = CACHE_TTL_HOURS } = {}) {
  await mkdir(CACHE_DIR, { recursive: true });
  const cacheFile = path.join(
    CACHE_DIR,
    url.replace(/[^a-z0-9]+/gi, "_").slice(0, 120) + ".json"
  );
  if (existsSync(cacheFile)) {
    const cached = JSON.parse(await readFile(cacheFile, "utf8"));
    const ageHours = (Date.now() - cached.__fetchedAt) / 3.6e6;
    if (ageHours < ttlHours) {
      console.log(`  (cache hit, ${ageHours.toFixed(1)}h old) ${url}`);
      return cached.body;
    }
  }
  console.log(`  GET ${url}`);
  const res = await fetch(url, {
    headers: { "User-Agent": "personal-sports-calendar (non-commercial)" },
  });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  const body = await res.json();
  await writeFile(
    cacheFile,
    JSON.stringify({ __fetchedAt: Date.now(), body }, null, 2)
  );
  return body;
}

const OVERRIDES_FILE = () => path.join(DATA_DIR, "broadcast-overrides.json");

export async function loadBroadcastOverrides() {
  try {
    return JSON.parse(await readFile(OVERRIDES_FILE(), "utf8"));
  } catch {
    return { defaults: {}, events: {} };
  }
}

/**
 * TV/stream network for an event. Lookup order:
 *   per-event override -> per-competition default -> apiValue -> null ("TBD")
 */
export function resolveBroadcast(overrides, eventId, competition, apiValue) {
  return (
    overrides.events?.[eventId] ??
    overrides.defaults?.[competition] ??
    apiValue ??
    null
  );
}

export async function writeSource(file, payload) {
  await mkdir(DATA_DIR, { recursive: true });
  await writeFile(
    path.join(DATA_DIR, file),
    JSON.stringify(payload, null, 2)
  );
}

/** Merge every existing per-source file into data/events.json + data/events.js. */
export async function rebuildCombined() {
  let allEvents = [];
  for (const file of SOURCE_FILES) {
    const p = path.join(DATA_DIR, file);
    if (!existsSync(p)) continue;
    const parsed = JSON.parse(await readFile(p, "utf8"));
    allEvents = allEvents.concat(parsed.events ?? []);
  }
  allEvents.sort((a, b) => a.start_utc.localeCompare(b.start_utc));

  const combined = {
    generated: new Date().toISOString(),
    viewer_tz: VIEWER_TZ,
    count: allEvents.length,
    events: allEvents,
  };
  await writeFile(
    path.join(DATA_DIR, "events.json"),
    JSON.stringify(combined, null, 2)
  );
  await writeFile(
    path.join(DATA_DIR, "events.js"),
    `// Auto-generated by scripts/fetch-*.mjs - do not edit by hand.\n` +
      `window.SPORTS_CALENDAR_DATA = ${JSON.stringify(combined, null, 2)};\n`
  );
  console.log(
    `Rebuilt data/events.json + data/events.js (${allEvents.length} total events).`
  );
  return combined;
}
